lxq:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 123.249.101.149
    port: 3306
    database: self_driving
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    access-key-id: ************************
    access-key-secret: **************************
    bucket-name: self-driving
