spring:
  profiles:
    active: dev
  application:
    name: self-driving
  datasource:
    username: ${lxq.datasource.username}
    password: ${lxq.datasource.password}
    url: jdbc:mysql://${lxq.datasource.host}:${lxq.datasource.port}/${lxq.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: ${lxq.datasource.driver-class-name}
    type: com.alibaba.druid.pool.DruidDataSource
logging:
  level:
    com.lxq: debug

server:
  port: 8080
  servlet:
    context-path: /

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lxq.pojo
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: isDeleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

lxq:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    user-secret-key: lixiaoqing
    # 设置jwt过期时间
    user-ttl: 7200000
    # 设置前端传递过来的令牌名称
    user-token-name: token


